spring:
  security:
    user:
    name: test
    password: test
    Roles: ADMIN
  application:
    name: task
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/taskdb
    username: task
    password: p@ssw0rd
mail:
  host: smtp.example.com
  port: 587
  username: test@gmail.com
  password: testpassword
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
  receiver: recipient-email@example.com

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082
